name: Deploy Prato Rápido SaaS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job de Verificação Básica
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mysqli, pdo, pdo_mysql, gd, zip
    
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Check PHP syntax
      run: find . -name "*.php" -exec php -l {} \;
    
    - name: Verify CodeIgniter structure
      run: |
        test -f index.php
        test -f vercel.json
        test -d app
        test -d public

  # Job de Notificação de Deploy
  notify:
    runs-on: ubuntu-latest
    needs: check
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy Status
      run: |
        echo "✅ Código verificado com sucesso!"
        echo "📦 Pronto para deploy na Vercel"
        echo "🔗 Acesse: https://vercel.com para fazer o deploy manual"